#!/bin/bash
#SBATCH -A OD-224622
#SBATCH --job-name=vcftools
#SBATCH --time=1-00:00:00
#SBATCH --out %A_%a.out
#SBATCH --mem=64gb
#SBATCH --ntasks=16
#SBATCH --array=1
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=grace.fang@csiro.au
#SBATCH --dependency=singleton


# load required modules
module load vcftools/
module load htslib


# Update the below to be specific for each run:
################################
sample=$(sed -n ${SLURM_ARRAY_TASK_ID}p /scratch3/fan048/scratch1/Amanda_AGRF/arm_bam/bam/freebayes/samples.list)
input_dir=/scratch3/fan048/scratch1/Amanda_AGRF/arm_bam/bam/snpEff
output_dir=/scratch3/fan048/scratch1/Amanda_AGRF/arm_bam/bam/snpEff_filtered


echo '======'
echo ${sample}
echo ${input_dir}
echo ${output_dir}
echo ${input_dir}/${sample}-Ha.bam-sort.bam-marked.bam-RG.bam-Ha-freebayes.vcf.gz-norm.vcf.gz-DBS.vcf.gz-snpEff.vcf.gz
echo '======'

vcftools --gzvcf ${input_dir}/${sample}-Ha.bam-sort.bam-marked.bam-RG.bam-Ha-freebayes.vcf.gz-norm.vcf.gz-DBS.vcf.gz-snpEff.vcf.gz \
--minQ 20 --minDP 10 --recode --stdout | gzip -c > ${output_dir}/${sample}-Ha.bam-sort.bam-marked.bam-RG.bam-Ha-freebayes.vcf.gz-norm.vcf.gz-DBS.vcf.gz-snpEff.vcf.gz-vcftools.vcf.gz
